# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmployeeApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 120)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginLine = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLine.setText("")
        self.loginLine.setObjectName("loginLine")
        self.verticalLayout.addWidget(self.loginLine)
        self.passwordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLine.setObjectName("passwordLine")
        self.verticalLayout.addWidget(self.passwordLine)
        self.signInBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.signInBtn.setFont(font)
        self.signInBtn.setObjectName("signInBtn")
        self.verticalLayout.addWidget(self.signInBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Authorization", "Authorization"))
        self.loginLine.setPlaceholderText(_translate("MainWindow", "Login"))
        self.passwordLine.setPlaceholderText(_translate("MainWindow", "Password"))
        self.signInBtn.setText(_translate("MainWindow", "Sign in"))
